FROM python:3.11-alpine
WORKDIR /app

# Увеличиваем таймаут pip для медленного соединения
ENV PIP_DEFAULT_TIMEOUT=120

COPY backend/requirements.txt .
RUN pip install --no-cache-dir --default-timeout=120 -r requirements.txt
COPY backend/ .
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
